---
- name: Network Getting Started First Playbook
  hosts: linux
  become: true
  tasks:
    - name: update apt repository index
      apt:
        update_cache: yes

    - name: ensure vim is there
      apt:
        name: vim
        state: latest
