---
- name: Main point to run all tasks
  hosts: linux
  become: yes

- hosts: linux
  roles:
    - role: essential
      tags:
        - essential

    - role: docker
      tags:
        - docker

    # containers
    - role: containers/pihole
      when: enable_pihole | default(False)
      tags:
        - pihole
        - containers
