---
- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install required system packages
  package:
    state: latest
    name: "{{ docker_deps }}"

# - name: Install Docker (Ubuntu)
#   when: ansible_facts['distribution'] == 'Ubuntu'
#   block:
#     - name: Add Docker GPG apt Key
#       apt_key:
#         url: https://download.docker.com/linux/ubuntu/gpg
#         state: present

#     - name: Add Docker Repository
#       apt_repository:
#         repo: deb https://download.docker.com/linux/ubuntu bionic stable
#         state: present

- name: Ensure group docker exists
  group:
    name: docker
    state: present

# - name: Add user nmalish to group docker
#   user:
#     name: "ludka"
#     groups:
#       - docker
#     append: yes

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Make sure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
