---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "evanbuss/openbooks"
    pull: yes
    state: "started"
    labels:
      "flame.type": "application"
      "flame.name": "{{ dashboard_name }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    env:
      "TZ": "{{ timezone }}"
    ports: # to remome
      - "3000:80/tcp" # temp solution
    restart_policy: unless-stopped

- name: Add {{ container_name }} to the SWAG network (reverse-proxy)
  docker_network:
    name: swag_network
    connected:
      - "{{ container_name }}"
    appends: yes
  when: enable_swag
